version: 0.2

run-as: Linux-user-name

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo `Linux-user-name`
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo building
  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - target\spring-boot-todo-rest-api-h2-aws-codepipeline-0.0.1-SNAPSHOT.jar

